/**
 * TODO: Replace null prices with confirmed restaurant pricing before enabling real payment checkout.
 */
import type { MenuItem } from "./schema";

const tacoProteinGroup = {
  id: "protein",
  label: "Protein",
  required: true,
  options: [
    "Asada / Steak",
    "Pastor / Marinated Pork",
    "Tripa / Tripe",
    "Birria / Stewed Beef",
    "Pollo / Chicken",
  ],
};

const burroProteinGroup = {
  id: "protein",
  label: "Protein",
  required: true,
  options: ["Asada / Steak", "Pastor / Marinated Pork"],
};

const quesadillaStyleGroup = {
  id: "style",
  label: "Style",
  required: true,
  options: [
    "Asada",
    "Queso",
    "Sincronisadas",
    "Nopal con Tortilla",
    "Hongos con Tortilla",
  ],
};

const tortaStyleGroup = {
  id: "style",
  label: "Style",
  required: true,
  options: ["Asada / Steak", "Pastor / Marinated Pork", "Cubana", "Jamon"],
};

export const localMenuItems: MenuItem[] = [
  {
    id: "tacos-choice",
    active: true,
    category: "Tacos",
    sortOrder: 1,
    name: "Tacos",
    description:
      "Choice of Asada/Steak, Pastor/Marinated Pork, Tripa/Tripe, Birria/Stewed Beef, or Pollo/Chicken. Made with cilantro and onions.",
    price: 1.99,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
    optionGroups: [tacoProteinGroup],
  },
  {
    id: "taco-asada",
    active: true,
    category: "Tacos",
    sortOrder: 2,
    name: "Asada Taco",
    description: "Steak, cilantro, and onions.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
  },
  {
    id: "taco-pastor",
    active: true,
    category: "Tacos",
    sortOrder: 3,
    name: "Pastor Taco",
    description: "Marinated pork, cilantro, and onions.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
  },
  {
    id: "taco-pollo",
    active: true,
    category: "Tacos",
    sortOrder: 4,
    name: "Pollo Taco",
    description: "Chicken, cilantro, and onions.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
  },
  {
    id: "taco-nopal",
    active: true,
    category: "Tacos",
    sortOrder: 5,
    name: "Nopal Taco",
    description: "Grilled cactus with classic taco fixings.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
  },
  {
    id: "taco-brisket-cheese",
    active: true,
    category: "Tacos",
    sortOrder: 6,
    name: "Brisket & Cheese Taco",
    description: "Brisket with melted cheese — confirm build and price with kitchen.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
  },
  {
    id: "taco-quesabirria",
    active: true,
    category: "Tacos",
    sortOrder: 7,
    name: "Quesabirria Tacos",
    description: "Stewed beef and cheese — confirm order style and consommé with kitchen.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
  },
  {
    id: "burros-choice",
    active: true,
    category: "Burros",
    sortOrder: 1,
    name: "Burros",
    description:
      "Choice of Asada/Steak or Pastor/Marinated Pork. Includes sour cream, lettuce, beans, and pico de gallo.",
    price: 7.25,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
    optionGroups: [burroProteinGroup],
  },
  {
    id: "burro-pastor",
    active: true,
    category: "Burros",
    sortOrder: 2,
    name: "Pastor Burrito",
    description: "Pastor burrito — confirm toppings and price with kitchen.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
  },
  {
    id: "quesadillas-choice",
    active: true,
    category: "Quesadillas",
    sortOrder: 1,
    name: "Quesadillas",
    description:
      "Choice of Asada, Queso, Sincronisadas, Nopal con Tortilla, or Hongos con Tortilla. Made with cilantro and onions.",
    price: 6.99,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
    optionGroups: [quesadillaStyleGroup],
  },
  {
    id: "queso-quesadilla",
    active: true,
    category: "Quesadillas",
    sortOrder: 2,
    name: "Queso",
    description: "Cheese quesadilla — confirm format with kitchen.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
  },
  {
    id: "sincronisadas",
    active: true,
    category: "Quesadillas",
    sortOrder: 3,
    name: "Sincronisadas",
    description: "Ham and cheese sincronizadas.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
  },
  {
    id: "nopal-quesadilla",
    active: true,
    category: "Quesadillas",
    sortOrder: 4,
    name: "Nopal",
    description: "Grilled cactus quesadilla — confirm price with kitchen.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
  },
  {
    id: "tortas-choice",
    active: true,
    category: "Tortas",
    sortOrder: 1,
    name: "Tortas",
    description:
      "Choice of Asada/Steak, Pastor/Marinated Pork, Cubana, or Jamon. Includes lettuce and tomatoes.",
    price: 7.25,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
    optionGroups: [tortaStyleGroup],
  },
  {
    id: "torta-pastor",
    active: true,
    category: "Tortas",
    sortOrder: 2,
    name: "Pastor Torta",
    description: "Pastor torta — confirm build and price with kitchen.",
    price: null,
    includesFries: false,
    meatChoiceRequired: false,
    featured: true,
  },
  {
    id: "side-frijoles",
    active: true,
    category: "Sides",
    sortOrder: 1,
    name: "Frijoles",
    price: 1.99,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "side-arroz",
    active: true,
    category: "Sides",
    sortOrder: 2,
    name: "Arroz",
    price: 1.99,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "side-toreados",
    active: true,
    category: "Sides",
    sortOrder: 3,
    name: "Toreados",
    price: 2.99,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "side-guacamole",
    active: true,
    category: "Sides",
    sortOrder: 4,
    name: "Guacamole",
    price: 3.5,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "side-sour-cream",
    active: true,
    category: "Sides",
    sortOrder: 5,
    name: "Sour Cream",
    price: 0.99,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "side-pico",
    active: true,
    category: "Sides",
    sortOrder: 6,
    name: "Pico de Gallo",
    price: 1.25,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "dessert-paletas",
    active: true,
    category: "Desserts",
    sortOrder: 1,
    name: "Paletas",
    price: 1.99,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "dessert-triple-chocolate",
    active: true,
    category: "Desserts",
    sortOrder: 2,
    name: "Triple Chocolate Cake",
    price: 3.5,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "drink-cidral",
    active: true,
    category: "Drinks",
    sortOrder: 1,
    name: "Cidral",
    price: 1.99,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "drink-coke",
    active: true,
    category: "Drinks",
    sortOrder: 2,
    name: "Coke",
    price: 2.25,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "drink-fanta",
    active: true,
    category: "Drinks",
    sortOrder: 3,
    name: "Fanta",
    price: 2.25,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
  {
    id: "drink-jarritos",
    active: true,
    category: "Drinks",
    sortOrder: 4,
    name: "Jarritos",
    price: 1.99,
    includesFries: false,
    meatChoiceRequired: false,
    featured: false,
  },
];
