/**
 * Local fallback menu — generated from Menufy snapshot (location 32419).
 * Source: prompt/menufy-location-32419-categories-all.json
 * Regenerate: node scripts/build-menu-from-menufy-snapshot.mjs
 * PIZADILLA rows have itemPriceHasUpgrades in Menufy; modifier prices are NOT in categories/all — no optionGroups until owner maps upgrades.
 */
import type { MenuItem } from "./schema";

export const localMenuItems: MenuItem[] = [
  {
    "id": "mf-7255491",
    "active": true,
    "category": "Tacos",
    "section": "",
    "sortOrder": 1,
    "name": "Asada (Steak)",
    "price": 3.25,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255492",
    "active": true,
    "category": "Tacos",
    "section": "",
    "sortOrder": 2,
    "name": "Pastor (Marinated Pork)",
    "price": 3.25,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255494",
    "active": true,
    "category": "Tacos",
    "section": "",
    "sortOrder": 3,
    "name": "Pollo (Chicken)",
    "price": 3.25,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8041768",
    "active": true,
    "category": "Tacos",
    "section": "",
    "sortOrder": 4,
    "name": "Chorizo",
    "price": 3.25,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8041769",
    "active": true,
    "category": "Tacos",
    "section": "",
    "sortOrder": 5,
    "name": "Cactus (Nopal)",
    "price": 3.49,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255495",
    "active": true,
    "category": "Tacos",
    "section": "",
    "sortOrder": 6,
    "name": "Quesabirria",
    "description": "Brisket & cheese.",
    "price": 3.49,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": true
  },
  {
    "id": "mf-7255493",
    "active": true,
    "category": "Tacos",
    "section": "",
    "sortOrder": 7,
    "name": "Birria (Stewed Beef)",
    "description": "Brisket.",
    "price": 3.49,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": true
  },
  {
    "id": "mf-12772871",
    "active": true,
    "category": "Tacos",
    "section": "",
    "sortOrder": 8,
    "name": "Tripe",
    "price": 3.49,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-12772872",
    "active": true,
    "category": "Tacos",
    "section": "",
    "sortOrder": 9,
    "name": "Tongue",
    "price": 3.49,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-12772873",
    "active": true,
    "category": "Tacos",
    "section": "",
    "sortOrder": 10,
    "name": "Campechano",
    "price": 3.49,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255496",
    "active": true,
    "category": "Burritos",
    "section": "",
    "sortOrder": 1,
    "name": "Asada (Steak)",
    "price": 10.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8041841",
    "active": true,
    "category": "Burritos",
    "section": "",
    "sortOrder": 2,
    "name": "Pollo (Chicken)",
    "price": 10.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8041842",
    "active": true,
    "category": "Burritos",
    "section": "",
    "sortOrder": 3,
    "name": "Chorizo",
    "price": 10.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255497",
    "active": true,
    "category": "Burritos",
    "section": "",
    "sortOrder": 4,
    "name": "Pastor (Marinated Pork)",
    "price": 10.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8041843",
    "active": true,
    "category": "Burritos",
    "section": "",
    "sortOrder": 5,
    "name": "Birria Burrito",
    "price": 11.49,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": true
  },
  {
    "id": "mf-11272021",
    "active": true,
    "category": "Burritos",
    "section": "",
    "sortOrder": 6,
    "name": "Nopal (Cactus)",
    "price": 11.49,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-11272022",
    "active": true,
    "category": "Burritos",
    "section": "",
    "sortOrder": 7,
    "name": "Mamalon",
    "price": 13.25,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255499",
    "active": true,
    "category": "Tortas",
    "section": "",
    "sortOrder": 1,
    "name": "Asada (Steak)",
    "price": 10.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8042238",
    "active": true,
    "category": "Tortas",
    "section": "",
    "sortOrder": 2,
    "name": "Pollo (Chicken)",
    "price": 10.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255500",
    "active": true,
    "category": "Tortas",
    "section": "",
    "sortOrder": 3,
    "name": "Pastor (Marinated Pork)",
    "price": 10.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255501",
    "active": true,
    "category": "Tortas",
    "section": "",
    "sortOrder": 4,
    "name": "Cubana Jamon",
    "price": 11.5,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8042242",
    "active": true,
    "category": "Tortas",
    "section": "",
    "sortOrder": 5,
    "name": "Cubana Torta",
    "price": 11.49,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8042243",
    "active": true,
    "category": "Tortas",
    "section": "",
    "sortOrder": 6,
    "name": "Megladon Torta",
    "price": 13.25,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": true
  },
  {
    "id": "mf-12772876",
    "active": true,
    "category": "Tortas",
    "section": "",
    "sortOrder": 7,
    "name": "Chorizo",
    "price": 10.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-12772877",
    "active": true,
    "category": "Tortas",
    "section": "",
    "sortOrder": 8,
    "name": "Ham",
    "price": 11.5,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255502",
    "active": true,
    "category": "Quesadillas",
    "section": "",
    "sortOrder": 1,
    "name": "Asada (Steak)",
    "price": 9.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255503",
    "active": true,
    "category": "Quesadillas",
    "section": "",
    "sortOrder": 2,
    "name": "Queso",
    "price": 7.5,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8042058",
    "active": true,
    "category": "Quesadillas",
    "section": "",
    "sortOrder": 3,
    "name": "Pollo (Chicken)",
    "price": 9.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255504",
    "active": true,
    "category": "Quesadillas",
    "section": "",
    "sortOrder": 4,
    "name": "Sincronisadas",
    "price": 10.5,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": true
  },
  {
    "id": "mf-8042059",
    "active": true,
    "category": "Quesadillas",
    "section": "",
    "sortOrder": 5,
    "name": "Pork (Pastor)",
    "price": 9.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8042060",
    "active": true,
    "category": "Quesadillas",
    "section": "",
    "sortOrder": 6,
    "name": "Chorizo",
    "price": 9.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255505",
    "active": true,
    "category": "Quesadillas",
    "section": "",
    "sortOrder": 7,
    "name": "Nopal (Corn Tortilla)",
    "price": 9.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8042061",
    "active": true,
    "category": "Quesadillas",
    "section": "",
    "sortOrder": 8,
    "name": "Ham (Jamon)",
    "price": 10.5,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-11272024",
    "active": true,
    "category": "Quesadillas",
    "section": "",
    "sortOrder": 9,
    "name": "Calabaza",
    "price": 11.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-11272025",
    "active": true,
    "category": "Quesadillas",
    "section": "",
    "sortOrder": 10,
    "name": "Huitlacoche",
    "price": 11.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-12772875",
    "active": true,
    "category": "Quesadillas",
    "section": "",
    "sortOrder": 11,
    "name": "Cactus",
    "price": 11.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-12772874",
    "active": true,
    "category": "Quesadillas",
    "section": "",
    "sortOrder": 12,
    "name": "Squash Blossom",
    "price": 11.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8042253",
    "active": true,
    "category": "Pizadilla",
    "section": "",
    "sortOrder": 1,
    "name": "Asada (Steak)",
    "price": 14.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8042254",
    "active": true,
    "category": "Pizadilla",
    "section": "",
    "sortOrder": 2,
    "name": "Pollo (Chicken)",
    "price": 14.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8042255",
    "active": true,
    "category": "Pizadilla",
    "section": "",
    "sortOrder": 3,
    "name": "Pork (Pastor)",
    "price": 14.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8042256",
    "active": true,
    "category": "Pizadilla",
    "section": "",
    "sortOrder": 4,
    "name": "Chorizo",
    "price": 14.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8042257",
    "active": true,
    "category": "Pizadilla",
    "section": "",
    "sortOrder": 5,
    "name": "Vegetales (Vegetarian)",
    "price": 14.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-12772878",
    "active": true,
    "category": "Pizadilla",
    "section": "",
    "sortOrder": 6,
    "name": "Birria",
    "price": 14.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-12772879",
    "active": true,
    "category": "Pizadilla",
    "section": "",
    "sortOrder": 7,
    "name": "Brisket",
    "price": 15.98,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": true
  },
  {
    "id": "mf-8042268",
    "active": true,
    "category": "Combos",
    "section": "",
    "sortOrder": 1,
    "name": "#1. Burrito & 2 Tacos",
    "description": "Your choice of meat.",
    "price": 14.5,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": true,
    "optionGroups": [
      {
        "id": "meat",
        "label": "Choice of meat",
        "required": true,
        "options": [
          "Asada (Steak)",
          "Pastor (Marinated Pork)",
          "Pollo (Chicken)",
          "Chorizo",
          "Birria (Stewed Beef)"
        ]
      }
    ]
  },
  {
    "id": "mf-8042269",
    "active": true,
    "category": "Combos",
    "section": "",
    "sortOrder": 2,
    "name": "#2. Quesadilla & 2 Tacos",
    "description": "Your choice of meat.",
    "price": 13.5,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false,
    "optionGroups": [
      {
        "id": "meat",
        "label": "Choice of meat",
        "required": true,
        "options": [
          "Asada (Steak)",
          "Pastor (Marinated Pork)",
          "Pollo (Chicken)",
          "Chorizo",
          "Birria (Stewed Beef)"
        ]
      }
    ]
  },
  {
    "id": "mf-8042270",
    "active": true,
    "category": "Combos",
    "section": "",
    "sortOrder": 3,
    "name": "#3. Torta & 2 Tacos",
    "description": "Your choice of meat.",
    "price": 14.5,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false,
    "optionGroups": [
      {
        "id": "meat",
        "label": "Choice of meat",
        "required": true,
        "options": [
          "Asada (Steak)",
          "Pastor (Marinated Pork)",
          "Pollo (Chicken)",
          "Chorizo",
          "Birria (Stewed Beef)"
        ]
      }
    ]
  },
  {
    "id": "mf-8042271",
    "active": true,
    "category": "Combos",
    "section": "",
    "sortOrder": 4,
    "name": "#4. 3 Quesabirrias & 2 Tacos",
    "description": "Your choice of meat.",
    "price": 14.5,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": true,
    "optionGroups": [
      {
        "id": "meat",
        "label": "Choice of meat",
        "required": true,
        "options": [
          "Asada (Steak)",
          "Pastor (Marinated Pork)",
          "Pollo (Chicken)",
          "Chorizo",
          "Birria (Stewed Beef)"
        ]
      }
    ]
  },
  {
    "id": "mf-9708505",
    "active": true,
    "category": "Combos",
    "section": "",
    "sortOrder": 5,
    "name": "#5. 5 Quesabirrias with 1 Consomé",
    "price": 14.5,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-11272074",
    "active": true,
    "category": "Combos",
    "section": "",
    "sortOrder": 6,
    "name": "#6. 5 Tacos",
    "price": 12.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-11272075",
    "active": true,
    "category": "Combos",
    "section": "",
    "sortOrder": 7,
    "name": "#7. Quesadilla Flor de Calabaza",
    "price": 13.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-11272076",
    "active": true,
    "category": "Combos",
    "section": "",
    "sortOrder": 8,
    "name": "#8. 3 Quesabirrias, Arroz, Frijol, Consome",
    "price": 14.5,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-11272077",
    "active": true,
    "category": "Combos",
    "section": "",
    "sortOrder": 9,
    "name": "#9. Burrito Bowl",
    "price": 9.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-11272078",
    "active": true,
    "category": "Combos",
    "section": "",
    "sortOrder": 10,
    "name": "#10. Pizadilla",
    "price": 14.5,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-11272079",
    "active": true,
    "category": "Combos",
    "section": "",
    "sortOrder": 11,
    "name": "#11. 3 Tacos, Arroz, Frijol",
    "price": 10.5,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-11272080",
    "active": true,
    "category": "Combos",
    "section": "",
    "sortOrder": 12,
    "name": "#12. 5 Tacos Jaliscos",
    "price": 14.5,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-11272081",
    "active": true,
    "category": "Combos",
    "section": "",
    "sortOrder": 13,
    "name": "#13. 5 Tacos Mixtos",
    "price": 14.5,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-12772880",
    "active": true,
    "category": "Combos",
    "section": "",
    "sortOrder": 14,
    "name": "#14 Carne Asada Platter",
    "price": 13.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8042250",
    "active": true,
    "category": "Platters",
    "section": "",
    "sortOrder": 1,
    "name": "Family Platter",
    "description": "One burrito or torta with your choice of meat. Five tacos with your choice of meat, and one quesadilla with your choice of meat.",
    "price": 32.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": true
  },
  {
    "id": "mf-8042251",
    "active": true,
    "category": "Platters",
    "section": "",
    "sortOrder": 2,
    "name": "Quesabirrias (15)",
    "price": 42.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": true
  },
  {
    "id": "mf-8042252",
    "active": true,
    "category": "Platters",
    "section": "",
    "sortOrder": 3,
    "name": "Taco Platter (15)",
    "description": "Your choice of meat. Steak, chicken, pork or chorizo.",
    "price": 40,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false,
    "optionGroups": [
      {
        "id": "meat",
        "label": "Choice of meat",
        "required": true,
        "options": [
          "Asada (Steak)",
          "Pollo (Chicken)",
          "Pastor (Marinated Pork)",
          "Chorizo"
        ]
      }
    ]
  },
  {
    "id": "mf-11272023",
    "active": true,
    "category": "Sides",
    "section": "",
    "sortOrder": 1,
    "name": "Aguacate",
    "price": 2.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255514",
    "active": true,
    "category": "Sides",
    "section": "",
    "sortOrder": 2,
    "name": "Arroz",
    "price": 2.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255513",
    "active": true,
    "category": "Sides",
    "section": "",
    "sortOrder": 3,
    "name": "Frijoles",
    "price": 2.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255515",
    "active": true,
    "category": "Sides",
    "section": "",
    "sortOrder": 4,
    "name": "Toreados",
    "price": 2.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255516",
    "active": true,
    "category": "Sides",
    "section": "",
    "sortOrder": 5,
    "name": "Sour Cream",
    "price": 2,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255517",
    "active": true,
    "category": "Sides",
    "section": "",
    "sortOrder": 6,
    "name": "Pico De Gallo",
    "price": 2,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8042166",
    "active": true,
    "category": "Sides",
    "section": "",
    "sortOrder": 7,
    "name": "Extra Consome",
    "price": 1.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8042167",
    "active": true,
    "category": "Sides",
    "section": "",
    "sortOrder": 8,
    "name": "Extra Lime",
    "price": 2.49,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8042168",
    "active": true,
    "category": "Sides",
    "section": "",
    "sortOrder": 9,
    "name": "Extra Salsa",
    "price": 1.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255506",
    "active": true,
    "category": "Postres (Desserts)",
    "section": "",
    "sortOrder": 1,
    "name": "Triple Chocolate Cake",
    "price": 4.25,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255507",
    "active": true,
    "category": "Postres (Desserts)",
    "section": "",
    "sortOrder": 2,
    "name": "3 Leches Cake",
    "price": 4.25,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": true
  },
  {
    "id": "mf-7255508",
    "active": true,
    "category": "Postres (Desserts)",
    "section": "",
    "sortOrder": 3,
    "name": "Strawberry Cheesecake",
    "price": 4.25,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255509",
    "active": true,
    "category": "Bebidas (Drinks)",
    "section": "",
    "sortOrder": 1,
    "name": "Mexican Coke",
    "price": 3.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": true
  },
  {
    "id": "mf-8042099",
    "active": true,
    "category": "Bebidas (Drinks)",
    "section": "",
    "sortOrder": 2,
    "name": "Manzanita",
    "price": 2.5,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8042100",
    "active": true,
    "category": "Bebidas (Drinks)",
    "section": "",
    "sortOrder": 3,
    "name": "Sangria",
    "price": 2.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255510",
    "active": true,
    "category": "Bebidas (Drinks)",
    "section": "",
    "sortOrder": 4,
    "name": "Fanta",
    "price": 3.5,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255512",
    "active": true,
    "category": "Bebidas (Drinks)",
    "section": "",
    "sortOrder": 5,
    "name": "Sidral",
    "price": 2.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-8042102",
    "active": true,
    "category": "Bebidas (Drinks)",
    "section": "",
    "sortOrder": 6,
    "name": "Water",
    "price": 1.5,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  },
  {
    "id": "mf-7255511",
    "active": true,
    "category": "Bebidas (Drinks)",
    "section": "",
    "sortOrder": 7,
    "name": "Jarritos",
    "price": 2.99,
    "includesFries": false,
    "meatChoiceRequired": false,
    "featured": false
  }
];
